### ISSUE TITLE
TypeError: Cannot redefine property ...

### ISSUE THREAD

**Issue by mib008** [othiym23/shimmer#12]
```
TypeError: Cannot redefine property: pseudoRandomBytes
      at Function.defineProperty (<anonymous>)
      at defineProperty (node_modules/shimmer/index.js:14:10)
      at wrap (node_modules/shimmer/index.js:56:3)
      at node_modules/shimmer/index.js:76:7
      at Array.forEach (<anonymous>)
      at node_modules/shimmer/index.js:75:11
```

The error occurs when redefine property.

**Comment by watson** [comment]
This is because `pseudoRandomBytes` is a locked property that cannot be shimmed in Node.js 11. This module doesn't do that however. You should instead open this issue in the node module you're using that is trying to shim `pseudoRandomBytes`
