### ISSUE TITLE
Do not include .tap.js test files in NPM package

### ISSUE THREAD

**Issue by jez9999** [othiym23/shimmer#8]
Please update your NPM package to remove the .tap.js files - they are for testing only and do not belong in a released NPM package.

**Comment by SimonSchick** [comment]
Bump, the entire `test` folder should be excluded.
@othiym23

**Comment by othiym23** [comment]
Sorry, everybody, but I disagree. If, for whatever reason, you're using shimmer in front end code, feel free to exclude test files as part of your build steps, but I have found having the test files handy a number of times when debugging projects that depend on my packages. Thanks for your time.
